mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/spring/study/mapper/*.xml

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe  # Oracle 데이터베이스 URL 설정
    username: Test  # 데이터베이스 사용자 이름
    password: pass  # 데이터베이스 비밀번호
    driver-class-name: oracle.jdbc.OracleDriver  # 사용할 JDBC 드라이버 클래스명
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
